spring:
  datasource:
    url: jdbc:h2:mem:transaction_management_db
    driverClassName: org.h2.Driver
    username: user
    password: password

flyway:
  user: user
  password: password
  schemas: transaction_management_db
  url: jdbc:h2:mem:transaction_management_db
  locations: filesystem:src/main/resources/db/migration/